language: objective-c

before_install:
    - gem install xcpretty
    - gem install cocoapods --pre
    
script:
    - set -o pipefail
    - xcodebuild clean -workspace HXPhotoPicker-Demo.xcworkspace -scheme "HXPhotoPicker" -sdk iphonesimulator build | xcpretty
    - pod lib lint --verbose --allow-warnings --use-libraries

after_success:
    - sleep 3
    - bash <(curl -s https://codecov.io/bash)
