language: objective-c

before_install:
    - gem install xcpretty
    
script:
    - set -o pipefail
    - xcodebuild clean -workspace HXPhotoPicker-Demo.xcworkspace -scheme "HXPhotoPicker" -sdk iphonesimulator build | xcpretty

after_success:
    - sleep 4
    - bash <(curl -s https://codecov.io/bash)
